# Use the base Python image
FROM python:3.9-slim
# RUN apt-get update  && apt-get install -y git python3-virtualenv wget

WORKDIR /workspace

# installation of dependancies
COPY . /workspace/
RUN pip install -r requirements.txt


# RUN pip install -r tsotsa/requirements.txt

CMD ["python", "main.py", "--api", "incubating", "--comparison", "true", "--comparison_folder_path", "data/comparisons"]
